"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { onAuthStateChanged, signInWithPopup, signOut, type User } from "firebase/auth";
import { addDoc, collection, deleteDoc, doc, getDocs, orderBy, query as firestoreQuery, serverTimestamp, updateDoc } from "firebase/firestore";
import { Archive, BarChart3, Check, ChevronRight, Clock3, Gamepad2, Library, ListFilter, LogIn, LogOut, MoreHorizontal, Pencil, Plus, Search, Sparkles, Target, Trash2, Trophy, type LucideIcon } from "lucide-react";
import { toast } from "sonner";
import { auth, db, googleProvider, isFirebaseConfigured } from "./firebase";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Slider } from "@/components/ui/slider";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Toaster } from "@/components/ui/sonner";

type Game = { id:string; title:string; platform:string; format:string; status:string; progress:number; hours:number; priority:string; series:string; nextGoal:string; notes:string; updatedAt:string };
type Draft = Omit<Game, "id" | "updatedAt">;
const platforms = ["3DS", "Series S", "PS2", "GameCube", "GBA", "Switch", "PC", "Otra"];
const statuses = ["Jugando", "Backlog", "Pausado", "Terminado", "Completado", "Abandonado", "Pendiente de compra"];
const blank: Draft = { title:"", platform:"3DS", format:"Digital", status:"Backlog", progress:0, hours:0, priority:"Normal", series:"", nextGoal:"", notes:"" };
const statusStyle: Record<string,string> = { Jugando:"bg-cyan-400/10 text-cyan-300 border-cyan-400/20", Backlog:"bg-violet-400/10 text-violet-300 border-violet-400/20", Pausado:"bg-amber-400/10 text-amber-300 border-amber-400/20", Terminado:"bg-emerald-400/10 text-emerald-300 border-emerald-400/20", Completado:"bg-lime-400/10 text-lime-300 border-lime-400/20", Abandonado:"bg-slate-400/10 text-slate-300 border-slate-400/20", "Pendiente de compra":"bg-fuchsia-400/10 text-fuchsia-300 border-fuchsia-400/20" };
const color: Record<string,string> = { "3DS":"from-red-500 to-orange-400", "Series S":"from-emerald-500 to-green-300", PS2:"from-indigo-500 to-blue-400", GameCube:"from-violet-600 to-fuchsia-400", GBA:"from-sky-500 to-cyan-300", Switch:"from-rose-500 to-red-300", PC:"from-slate-500 to-slate-300", Otra:"from-amber-500 to-yellow-300" };

export function GameDashboard(){
  const [games,setGames]=useState<Game[]>([]), [loading,setLoading]=useState(true), [user,setUser]=useState<User|null>(null), [authReady,setAuthReady]=useState(false), [query,setQuery]=useState(""), [tab,setTab]=useState("Todos"), [platform,setPlatform]=useState("Todas"), [dialog,setDialog]=useState(false), [editing,setEditing]=useState<Game|null>(null), [draft,setDraft]=useState<Draft>(blank), [saving,setSaving]=useState(false);
  useEffect(()=>{
    if(!auth||!db){setLoading(false);setAuthReady(true);return}
    const authClient=auth, store=db;
    let fallback=window.setTimeout(()=>{setUser(authClient.currentUser);setAuthReady(true);setLoading(false)},4000);
    const unsubscribe=onAuthStateChanged(authClient,async current=>{window.clearTimeout(fallback);setUser(current);setAuthReady(true);if(!current){setGames([]);setLoading(false);return}setLoading(true);try{const snapshot=await getDocs(firestoreQuery(collection(store,"users",current.uid,"games"),orderBy("updatedAt","desc")));setGames(snapshot.docs.map(item=>{const data=item.data() as Omit<Game,"id"|"updatedAt">&{updatedAt?:{toDate?:()=>Date}|string};const updated=data.updatedAt;return {...data,id:item.id,updatedAt:typeof updated==="string"?updated:updated?.toDate?.().toISOString()??new Date().toISOString()} as Game}))}catch(error){console.error(error);toast.error("No pudimos cargar tu biblioteca.")}finally{setLoading(false)}});
    return()=>{window.clearTimeout(fallback);unsubscribe()}
  },[]);
  useEffect(()=>{
    const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options?:{signal:AbortSignal})=>void}}).modelContext;
    if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    context.registerTool({name:"list_game_collection",title:"Ver colección",description:"Devuelve los juegos visibles en la biblioteca con su estado y progreso.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({games:games.map(({id,title,platform,status,progress,nextGoal})=>({id,title,platform,status,progress,nextGoal}))})},{signal:lifecycle.signal});
    context.registerTool({name:"start_adding_game",title:"Añadir juego",description:"Abre el formulario visible para añadir un juego a la biblioteca.",inputSchema:{type:"object",properties:{title:{type:"string"}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const title=typeof input==="object"&&input&&"title" in input?String((input as {title?:unknown}).title??""):"";setEditing(null);setDraft({...blank,title});setDialog(true);return {opened:true,title}}},{signal:lifecycle.signal});
    return()=>lifecycle.abort();
  },[games]);
  const filtered=useMemo(()=>games.filter(g=>(tab==="Todos"||g.status===tab)&&(platform==="Todas"||g.platform===platform)&&(g.title+g.series+g.nextGoal).toLowerCase().includes(query.toLowerCase())),[games,tab,platform,query]);
  const stats=useMemo(()=>({total:games.length,active:games.filter(g=>g.status==="Jugando").length,done:games.filter(g=>["Terminado","Completado"].includes(g.status)).length,hours:games.reduce((s,g)=>s+g.hours,0)}),[games]);
  const statItems: Array<{Icon:LucideIcon;label:string;value:number}>=[{Icon:Library,label:"Biblioteca",value:stats.total},{Icon:Gamepad2,label:"Jugando",value:stats.active},{Icon:Trophy,label:"Terminados",value:stats.done},{Icon:Clock3,label:"Horas",value:stats.hours}];
  const consoleStats=useMemo(()=>platforms.map(p=>({p,n:games.filter(g=>g.platform===p).length})).filter(x=>x.n).sort((a,b)=>b.n-a.n),[games]);
  const openNew=()=>{setEditing(null);setDraft(blank);setDialog(true)};
  const openEdit=(g:Game)=>{setEditing(g);setDraft({...g});setDialog(true)};
  async function login(){if(!auth)return;try{await signInWithPopup(auth,googleProvider)}catch(error){console.error(error);toast.error("No pudimos iniciar sesión con Google.")}}
  async function logout(){if(auth)await signOut(auth)}
  async function save(){if(!draft.title.trim())return toast.error("Escribe el nombre del juego.");if(!user||!db)return toast.error("Inicia sesión para guardar.");setSaving(true);try{const now=new Date().toISOString();const payload={...draft,updatedAt:serverTimestamp()};if(editing){await updateDoc(doc(db,"users",user.uid,"games",editing.id),payload);setGames(x=>x.map(g=>g.id===editing.id?{...draft,id:editing.id,updatedAt:now}:g))}else{const created=await addDoc(collection(db,"users",user.uid,"games"),{...payload,createdAt:serverTimestamp()});setGames(x=>[{...draft,id:created.id,updatedAt:now},...x])}setDialog(false);toast.success(editing?"Partida actualizada":"Juego añadido a tu bóveda")}catch(error){console.error(error);toast.error("No pudimos guardar.")}finally{setSaving(false)}}
  async function remove(g:Game){if(!confirm(`¿Eliminar “${g.title}” de tu biblioteca?`)||!user||!db)return;try{await deleteDoc(doc(db,"users",user.uid,"games",g.id));setGames(x=>x.filter(v=>v.id!==g.id));toast.success("Juego eliminado")}catch{toast.error("No pudimos eliminarlo.")}}
  async function starters(){if(!user||!db)return;const list:Draft[]=[{...blank,title:"Dragon Quest VII: Fragmentos de un mundo olvidado",status:"Jugando",series:"Dragon Quest",priority:"Alta",nextGoal:"Continuar la historia y registrar el próximo objetivo"},{...blank,title:"Dragon Quest VIII: El periplo del Rey Maldito",status:"Backlog",series:"Dragon Quest",priority:"Alta",nextGoal:"Empezar la partida"},{...blank,title:"Dragon Quest VII Reimagined",platform:"Series S",status:"Pendiente de compra",series:"Dragon Quest",nextGoal:"Comprar cuando esté listo para jugarlo"}];setSaving(true);try{const made:Game[]=[];for(const item of list){const created=await addDoc(collection(db,"users",user.uid,"games"),{...item,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});made.push({...item,id:created.id,updatedAt:new Date().toISOString()})}setGames(made);toast.success("Tus Dragon Quest ya están listos")}catch(error){console.error(error);toast.error("No pudimos añadirlos.")}finally{setSaving(false)}}

  if(!isFirebaseConfigured)return <SetupNotice/>;
  if(!authReady)return <div className="grid min-h-screen place-items-center bg-[#07101f] text-slate-300">Preparando tu bóveda…</div>;
  if(!user)return <SignIn onSignIn={login}/>;

  return <div className="min-h-screen bg-[#07101f] text-slate-100"><Toaster position="top-right" richColors/>
    <header className="sticky top-0 z-30 border-b border-white/8 bg-[#07101f]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1500px] items-center gap-4 px-4 lg:px-8"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-gradient-to-br from-violet-500 to-cyan-400 shadow-[0_0_28px_rgba(139,92,246,.3)]"><Gamepad2 className="size-5"/></div><div><div className="font-black tracking-tight">MI BÓVEDA</div><div className="-mt-1 text-[10px] font-bold tracking-[.22em] text-cyan-300">GAMER</div></div></div><div className="ml-auto flex gap-2"><Button variant="outline" className="hidden border-white/10 bg-white/5 text-slate-200 sm:flex" onClick={()=>setTab("Jugando")}><Target/>Partidas activas</Button><Button className="bg-violet-500 text-white hover:bg-violet-400" onClick={openNew}><Plus/>Añadir juego</Button><Button variant="ghost" size="icon" aria-label="Cerrar sesión" title={`Cerrar sesión de ${user.email??"Google"}`} onClick={logout}><LogOut/></Button></div></div></header>
    <main className="mx-auto grid max-w-[1500px] gap-7 px-4 py-7 lg:grid-cols-[minmax(0,1fr)_310px] lg:px-8"><section className="min-w-0">
      <div className="mb-7 flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><p className="mb-2 text-sm font-semibold text-cyan-300">Tu centro de mando</p><h1 className="text-3xl font-black tracking-[-.04em] sm:text-4xl">¿Qué aventura sigue?</h1><p className="mt-2 text-slate-400">Organiza tu colección y retoma cada partida sin perder el hilo.</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{statItems.map(({Icon,label,value})=><div key={label} className="min-w-[110px] rounded-2xl border border-white/8 bg-white/[.045] px-3 py-3"><div className="flex items-center gap-2 text-xs text-slate-400"><Icon className="size-4 text-cyan-300"/>{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div>)}</div></div>
      <div className="mb-5 flex flex-col gap-3 rounded-2xl border border-white/8 bg-white/[.035] p-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-500"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar juego, saga u objetivo..." className="border-white/8 bg-[#0b1628] pl-10"/></div><Select value={platform} onValueChange={setPlatform}><SelectTrigger className="w-full border-white/8 bg-[#0b1628] md:w-44"><ListFilter/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Todas">Todas las consolas</SelectItem>{platforms.map(p=><SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectContent></Select></div>
      <Tabs value={tab} onValueChange={setTab} className="mb-5"><TabsList className="h-auto w-full justify-start overflow-x-auto rounded-xl border border-white/8 bg-[#0b1628] p-1">{["Todos","Jugando","Backlog","Pausado","Terminado","Completado"].map(s=><TabsTrigger key={s} value={s} className="min-w-max data-[state=active]:bg-violet-500 data-[state=active]:text-white">{s}</TabsTrigger>)}</TabsList></Tabs>
      {loading?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3,4,5,6].map(i=><Skeleton key={i} className="h-64 rounded-3xl bg-white/5"/>)}</div>:filtered.length===0?<Empty hasGames={!!games.length} reset={()=>{setQuery("");setTab("Todos");setPlatform("Todas")}} starters={starters} add={openNew} saving={saving}/>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(g=><GameCard key={g.id} game={g} edit={()=>openEdit(g)} remove={()=>remove(g)}/>)}</div>}
    </section><aside className="space-y-5"><div className="rounded-3xl border border-white/8 bg-white/[.04] p-5"><div className="mb-5 flex items-center gap-2"><BarChart3 className="size-5 text-cyan-300"/><h2 className="font-bold">Tu colección</h2></div>{consoleStats.length?<div className="space-y-4">{consoleStats.map(({p,n})=><button key={p} onClick={()=>setPlatform(p)} className="block w-full text-left"><div className="mb-1.5 flex justify-between text-sm"><span>{p}</span><span className="text-slate-400">{n} juego{n!==1?"s":""}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/8"><div className={`h-full rounded-full bg-gradient-to-r ${color[p]??color.Otra}`} style={{width:`${Math.max(10,n/Math.max(stats.total,1)*100)}%`}}/></div></button>)}</div>:<p className="text-sm text-slate-400">Aquí verás tu colección por consola.</p>}</div><div className="rounded-3xl border border-violet-400/20 bg-gradient-to-br from-violet-500/15 to-cyan-400/10 p-5"><div className="mb-3 grid size-10 place-items-center rounded-xl bg-violet-400/15 text-violet-300"><Target/></div><h2 className="font-bold">Regla de enfoque</h2><p className="mt-2 text-sm leading-6 text-slate-300">Mantén entre 3 y 5 partidas activas. Tu backlog puede ser enorme; tu atención no tiene que serlo.</p><div className="mt-4 flex items-center gap-2 text-sm font-semibold text-cyan-300">{stats.active<=5?<><Check className="size-4"/>Vas bien: {stats.active} activas</>:<>Tienes {stats.active} activas</>}</div></div></aside></main>
    <GameDialog open={dialog} setOpen={setDialog} draft={draft} setDraft={setDraft} editing={!!editing} save={save} saving={saving}/>
  </div>
}

function SignIn({onSignIn}:{onSignIn:()=>void}){return <main className="grid min-h-screen place-items-center bg-[#07101f] p-6 text-slate-100"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[.045] p-8 text-center shadow-2xl"><div className="mx-auto mb-5 grid size-16 place-items-center rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-400"><Gamepad2 className="size-8"/></div><h1 className="text-3xl font-black tracking-tight">Mi Bóveda Gamer</h1><p className="mt-3 leading-7 text-slate-400">Inicia sesión para acceder a tu colección. Tus juegos y tu progreso se guardan de forma privada en Google Cloud.</p><Button className="mt-7 w-full bg-violet-500 text-white hover:bg-violet-400" onClick={onSignIn}><LogIn/>Continuar con Google</Button></div></main>}
function SetupNotice(){return <main className="grid min-h-screen place-items-center bg-[#07101f] p-6 text-slate-100"><div className="max-w-lg rounded-3xl border border-amber-400/20 bg-amber-400/5 p-8"><h1 className="text-2xl font-black">Falta conectar Google Cloud</h1><p className="mt-3 leading-7 text-slate-300">La aplicación está lista. Añade la configuración pública de Firebase para activar el inicio de sesión y la base de datos.</p></div></main>}

function GameCard({game,edit,remove}:{game:Game;edit:()=>void;remove:()=>void}){return <article className="group overflow-hidden rounded-3xl border border-white/8 bg-gradient-to-b from-white/[.065] to-white/[.025] transition hover:-translate-y-1 hover:border-violet-400/30"><div className={`h-2 bg-gradient-to-r ${color[game.platform]??color.Otra}`}/><div className="p-5"><div className="flex items-start gap-3"><div className={`grid size-12 shrink-0 place-items-center rounded-2xl bg-gradient-to-br ${color[game.platform]??color.Otra} text-xs font-black`}>{game.platform.slice(0,3).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h2 className="line-clamp-2 font-bold leading-tight">{game.title}</h2><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="-mr-2 -mt-2 text-slate-400"><MoreHorizontal/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={edit}><Pencil/>Editar</DropdownMenuItem><DropdownMenuItem variant="destructive" onClick={remove}><Trash2/>Eliminar</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div><div className="mt-1 text-sm text-slate-400">{game.platform} · {game.format}</div></div></div><div className="mt-5 flex items-center justify-between"><Badge variant="outline" className={statusStyle[game.status]}>{game.status}</Badge><span className="text-sm font-bold">{game.progress}%</span></div><Progress value={game.progress} className="mt-3 h-2 bg-white/8 [&_[data-slot=progress-indicator]]:bg-gradient-to-r [&_[data-slot=progress-indicator]]:from-violet-500 [&_[data-slot=progress-indicator]]:to-cyan-400"/><div className="mt-5 min-h-14 rounded-xl bg-black/20 p-3"><div className="mb-1 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wider text-cyan-300"><Target className="size-3.5"/>Próximo objetivo</div><p className="line-clamp-2 text-sm text-slate-300">{game.nextGoal||"Añade una nota para recordar dónde continuar."}</p></div><div className="mt-4 flex items-center justify-between text-sm text-slate-400"><span className="flex items-center gap-1.5"><Clock3 className="size-4"/>{game.hours} h</span><Button variant="ghost" size="sm" className="-mr-2 text-violet-300" onClick={edit}>Actualizar<ChevronRight/></Button></div></div></article>}

function Empty({hasGames,reset,starters,add,saving}:{hasGames:boolean;reset:()=>void;starters:()=>void;add:()=>void;saving:boolean}){return <div className="grid min-h-[370px] place-items-center rounded-3xl border border-dashed border-white/12 bg-white/[.025] p-8 text-center"><div><div className="mx-auto mb-4 grid size-16 place-items-center rounded-2xl bg-violet-500/15 text-violet-300"><Archive className="size-8"/></div><h2 className="text-xl font-bold">{hasGames?"No hay coincidencias":"Tu bóveda está lista"}</h2><p className="mx-auto mt-2 max-w-md text-slate-400">{hasGames?"Prueba otro filtro o una búsqueda diferente.":"Empieza con los Dragon Quest que ya mencionaste o añade cualquier juego de tu colección."}</p>{hasGames?<Button className="mt-5" variant="outline" onClick={reset}>Limpiar filtros</Button>:<div className="mt-5 flex flex-col justify-center gap-2 sm:flex-row"><Button className="bg-violet-500" onClick={starters} disabled={saving}><Sparkles/>Cargar mis Dragon Quest</Button><Button variant="outline" className="border-white/10 bg-white/5" onClick={add}><Plus/>Añadir otro</Button></div>}</div></div>}

function GameDialog({open,setOpen,draft,setDraft,editing,save,saving}:{open:boolean;setOpen:(v:boolean)=>void;draft:Draft;setDraft:(d:Draft)=>void;editing:boolean;save:()=>void;saving:boolean}){return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[92vh] overflow-y-auto border-white/10 bg-[#0b1628] text-slate-100 sm:max-w-2xl"><DialogHeader><DialogTitle>{editing?"Actualizar partida":"Añadir juego"}</DialogTitle><DialogDescription className="text-slate-400">Guarda lo necesario para saber exactamente dónde continuar.</DialogDescription></DialogHeader><div className="grid gap-4 py-2 sm:grid-cols-2"><Field label="Juego" wide><Input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Ej. Dragon Quest VII"/></Field><Pick label="Consola" value={draft.platform} items={platforms} change={v=>setDraft({...draft,platform:v})}/><Pick label="Formato" value={draft.format} items={["Digital","Físico"]} change={v=>setDraft({...draft,format:v})}/><Pick label="Estado" value={draft.status} items={statuses} change={v=>setDraft({...draft,status:v})}/><Pick label="Prioridad" value={draft.priority} items={["Alta","Normal","Baja"]} change={v=>setDraft({...draft,priority:v})}/><Field label="Saga"><Input value={draft.series} onChange={e=>setDraft({...draft,series:e.target.value})} placeholder="Ej. Dragon Quest"/></Field><Field label="Horas jugadas"><Input type="number" min="0" value={draft.hours} onChange={e=>setDraft({...draft,hours:Number(e.target.value)})}/></Field><Field label={`Progreso · ${draft.progress}%`} wide><Slider value={[draft.progress]} onValueChange={v=>setDraft({...draft,progress:Array.isArray(v)?v[0]:v})} max={100} step={1} className="py-3"/></Field><Field label="Próximo objetivo" wide><Input value={draft.nextGoal} onChange={e=>setDraft({...draft,nextGoal:e.target.value})} placeholder="¿Qué debes hacer cuando vuelvas?"/></Field><Field label="Notas" wide><Textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} placeholder="Build, misión, ubicación, objetos pendientes..." className="min-h-24"/></Field></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button className="bg-violet-500" onClick={save} disabled={saving}>{saving?"Guardando...":editing?"Guardar cambios":"Añadir a la bóveda"}</Button></DialogFooter></DialogContent></Dialog>}
function Field({label,wide,children}:{label:string;wide?:boolean;children:ReactNode}){return <div className={`space-y-2 ${wide?"sm:col-span-2":""}`}><Label>{label}</Label>{children}</div>}
function Pick({label,value,items,change}:{label:string;value:string;items:string[];change:(v:string)=>void}){return <Field label={label}><Select value={value} onValueChange={change}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i} value={i}>{i}</SelectItem>)}</SelectContent></Select></Field>}
